config/routes.rb
Rails.application.routes.draw do
  get '/auth/github/callback' => 'sessions#create'
  root 'sessions#welcome'

  resources :users,only: [:new, :index, :show, :create]  do
    resources :wallets, only: [:index, :new, :show]
    #new route: users/1/wallets/new
    #show route: users/1/wallet/1
    #index users/1/wallets
    resources :transactions, only: [:index, :new, :show]
    #new users/1/transactions/new
    #show route: users/1/transaction/1
    #index users/1/transactions
  end
  resources :wallets, only: [:creat, :edit, :update]
  resources :transactions, only: [:create, :edit, :update]
  resources :coins , only: [:update]

  get "/signup", to: "users#new" #signup route displays users/new erb and post to
  get "/login", to: "sessions#new" # login route displays sessions/new #erb and post to login
  post "/login",   to: 'sessions#create'
  # the create method in sessions controller finds the user and #verifies the user using the authenticate method.
  get '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many :transactions
  has_many :wallets
  has_many :users, through: :transactions
  # accepts_nested_attributes_for :transactions
  #provides getter and setter method wallets_attributes
end

app/models/market_place.rb
class MarketPlace < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :holding, presence: true
  validates :market_value, presence: true
  validates :net_cost, presence: true
  belongs_to :coin, optional: true
  belongs_to :user
  accepts_nested_attributes_for :coin
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_many :transactions
  has_many :wallets
  has_many :coins, through: :transactions #transactions is the join table

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
      binding.pry
      user.password = SecureRandom.hex
      user.username = auth_hash.info.name
    end
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  belongs_to :user, optional: true
  belongs_to :coin, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  # new, create and home routes are not allowed unless user is logged in
  # before_action :require_logged_in, except: [:new, :create, :home]
  helper_method :current_user

  def logged_in?
    !!current_user
  end

  private
    # def require_logged_in
    #   redirect_to root unless logged_in?
    # end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index
    @coins = Coin.all
  end

  def new
    
  end

  def create

  end

  def show

  end

  private

  def params_coin
    params.require(:coin).permit(:name, :price)
  end
end

app/controllers/market_places_controller.rb
class MarketPlacesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    @users = User.all
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      @user = User.find_by(username: params[:sessions][:username])
      if @user && @user.authenticate(params[:sessions][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
        #redirects to users/id path displays users/show erb
      else
        flash[:notice]  = 'Invalid email/password combination'
        render 'new'
      end
    end
  end

  def welcome

  end

  def destroy
    reset_session
    #session.delete :user_id
    redirect_to login_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transaction = Transaction.all
  end

  def new
    if logged_in?
      @transaction = Transaction.new
      @coin = Coin.new
    else
      redirect_to login_path
    end
  end

  def create
    if logged_in?
      @transaction =  current_user.transactions.create(params_transactions)
      if @transaction.save
        redirect_to user_transaction_path(@transaction.user_id, @transaction.id)
      else
        redirect_to new_user_transactions_path(@transaction.user_id)
      end
    else
      redirect_to login_path
    end
  end

  def show
    if logged_in?
      @transaction = current_user.transactions.find_by(id: params[:id])
      @coin = current_user.coins.find_by(id: params[:id])
      @wallet = current_user.wallets.find_by(id: params[:id])
    else
      redirect_to login_path
    end
  end

  private

  def params_transactions
    params.require(:transaction).permit(:holding, :market_value, :net_cost, coin_attributes:[:name, :price])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #set_user method called before the action.this allows to not have to #repeat the code.
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @user = User.find_by(:id)
  end
  def new
    @user = User.new
  end

#creating a new user using perms from stong method user_perms
  def create
    @user = User.create(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
      #redirects to user/:id
    end
  end

  def show
    if logged_in? === false
      redirect_to login_path
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

#prevents hacker from entering different perms then then one in the app
  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def index
    @wallets = current_user.wallets.all
  end

  def new
    if logged_in?
      @wallet = Wallet.new(user_id: params[:user_id])
    else
      redirect_to login_path
    end
  end

  def create
    @wallet =  current_user.wallets.create(wallet_params)
    if @wallet.save
      redirect_to user_wallet_path(@wallet.user_id, @wallet.id)
      #proving user id and wallet id for nested route #user/:id/wallet/:id
    else
      flash[:notice] = "Wallet name is required"
      redirect_to new_user_wallet_path(@wallet.user_id)
    end
  end

  def show
    if logged_in?
      @wallet = current_user.wallets.find_by(id: params[:id])
    else
      redirect_to login_path
    end
  end

  private

  def set_wallet
    @wallet = Wallet.find_by(id: params[:id])
  end

  def wallet_params
    params.require(:wallet).permit(:name, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/market_places_helper.rb
module MarketPlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/coins/new.html.erb
<%= current_user.username %><br>
<a href="/logout">Log Out</a>

<br><br>

app/views/coins/show.html.erb
<%= @wallet.name %>
<%@coin.wallets.each do |att| %>
  Holding: <%= att.holding %><br>
  Net Cost: <%= att.net_cost %><br>
  Holding: <%= att.market_value %><br>
<%end%>
Coin Name: <%= @coin.name %><br>
Coin Price: <%= @coin.price %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCryptocurrencyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/new.html.erb
<%= current_user.username %><br>
<a href="/logout">Log Out</a>
<br><br>
<%= form_for @transaction do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.fields_for :coin, @coin do |coin| %><br>
    Coin Name: <%= coin.text_field :name %><br>
    Coin Price: <%= coin.text_field :price %><br>
  <%end%>
    Holding: <%= f.text_field :holding %><br>
    Martet Value: <%= f.text_field :market_value %><br>
    Net Cost: <%= f.text_field :net_cost %><br>
  <br><br>
<%= f.submit "Create New Coin" %>
<% end %>

app/views/transactions/show.html.erb
User: <%= current_user.username %><br>
<h1>Wallet Name: <%= @wallet.name %><br></h1>

<h3>Wallet Name: <%= @wallet.name %><br><h3/>
<h3>Coin Name: <%= @coin.name %><br><h3/>
<h3>Coin Price: <%= @coin.price %><br><h3/>
<h3>Holding: <%= @transaction.holding %><br><h3/>
<h3>Cost: <%= @transaction.net_cost %><br><h3/>
<h3>Market Value : <%= @transaction.market_value %><h3/>

app/views/users/index.html.erb
<a href="/logout">Log Out</a>

app/views/users/new.html.erb
<h1>Create New User</h1>
<h3><p><%= link_to "Sign In", login_path %></p> </h3>
<% @user.errors.each do |attr,msg|  %>
 <%=attr %> <%=msg %>
<% end %>

<%= form_for @user do |f| %>
Username: <%= f.text_field :username %><br>
Password: <%= f.password_field :password %><br>
Email: <%= f.text_field :email %>
<br><br>
<%= f.submit "Sign up" %>
<%end%>

app/views/users/show.html.erb
<h3>Welcome <%= @user.username.capitalize %></h3>

<a href="/logout">Log Out</a>
<%= link_to "Create New Wallet",  new_user_wallet_path(@user.id)%>
<%= link_to "Show wallets", user_wallets_path(@user)%>

app/views/users/signin.html.erb
<h2>Sign In</h2>

<%= link_to('Log in with Github!', '/auth/gitgub') %>

<%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
  Username: <%= f.text_field :username %><br>
  Password: <%= f.password_field :password %>
  <br><br>
  <%= f.submit "Sign In" %>
<% end %>

app/views/wallets/index.html.erb
<a href="/logout">Log Out</a><br>
<% @wallets.each do |wallet| %>
  <% if current_user %>
    <%= link_to "Show #{wallet.name}", wallet_path(wallet) %>
  <% end %>
<% end %>

app/views/wallets/new.html.erb
<a href="/logout">Log Out</a>

<% if flash[:notice] -%>
  <p class="notice"><%= flash[:notice] %></p>
<% end -%>
<% if flash[:error] -%>
  <p class="error"><%= flash[:error] %></p>
<% end -%>


<%= form_for @wallet do |f| %>
Wallet Name: <%= f.text_field :name %>
<%= f.hidden_field :user_id %>
<br><br>
<%= f.submit "Create New Wallet" %>
<% end %>

app/views/wallets/show.html.erb
<h2>Wallet Name: <%= @wallet.name %></h2>
<h3><%= link_to "Add a coin", new_user_transaction_path(@wallet.user_id) %></h3>